apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: 339712706100.dkr.ecr.us-east-1.amazonaws.com/demo-microservice:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: demo-service

spec:
  selector:
    app: demo
  ports:

    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
